const numero1 = 20;
const numero3 = 30;

console.log(numero1);

try {
    console.log(numero2); //Hace que al dar error no se detenga el programa pero muestre el error
} catch (error) {
    console.log(error);
}


console.log(numero3);